### ISSUE TITLE
Testing views that render react components

### ISSUE THREAD

**Issue by tristanoneil** [airbnb/hypernova-ruby#3]
When testing a view that calls `render_react_component` the spec throws the following error.

```
Failure/Error: render
ActionView::Template::Error:
called hypernova_batch_render without calling hypernova_batch_before. Check your around_filter for :hypernova_render_support
```

This is because view specs use `ActionView::TestCase::TestController` so the `around_filter` isn't being called. I suppose I could stub out `render_react_component` but this seems less than ideal. Is there a work around for this or does it need to be addressed in the gem itself?

**Comment by ljharb** [comment]
I think stubbing that method is the right approach - generally rspec tests always have to stub their own filters.

**Comment by tristanoneil** [comment]
@ljharb Yea I guess this is a reasonable solution. Thanks!
