### ISSUE TITLE
[Question] How can I run the test?

### ISSUE THREAD

**Issue by gfx** [airbnb/hypernova-ruby#8]
I'm trying to create a patch but rspec fails because `http://mordor.com:1337/batch` does not work.

How can I run the test? I think some inevitable testing components are missing from the repo.

**Comment by ljharb** [comment]
`bundle exec rake spec` seems to pass for me - which test is failing for you?

**Comment by ljharb** [comment]
Also, what version of ruby are you using? Currently we only test with v1.9.3.

**Comment by ljharb** [comment]
This is because our tests were pinned to faraday 0.9 implicitly; I've bumped that to 0.10.

Tests should pass now, on ruby 1.9 - 2.2.

**Comment by gfx** [comment]
Test passes. Thanks.
